pipeline:

  npm-audit:
    group: build
    image: node:12
    commands:
      - npm audit --audit-level=moderate --only=prod
    when:
      event: push

  build-docker-image:
    group: build
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t pttg-euro-tlr-enquiry-form .
    when:
      event: push

  lint:
    group: build
    image: quay.io/ukhomeofficedigital/nodejs-base:v8.11.1
    commands:
      - npm install eslint
      - npm run test:lint
    when:
      event: push

  build-test:
    group: build
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile_test -t test-$${DRONE_COMMIT_SHA} .
    when:
      event: push

  scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    dockerfile: Dockerfile
    image_name: pttg-euro-tlr-enquiry-form
    local_image: true
    tolerate: low
    show_all_vulnerabilities: true
    fail_on_detection: false # TODO EE-29635 Remove this when current vulnerabilities are resolved
    when:
      event: push

  test:
    group: test
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -d --name=redis-$${DRONE_COMMIT_SHA} redis
      - docker run -d -e NODE_ENV=ci --name=app-$${DRONE_COMMIT_SHA} --net=container:redis-$${DRONE_COMMIT_SHA} pttg-euro-tlr-enquiry-form
      - docker run -d --net=container:app-$${DRONE_COMMIT_SHA} --name=selenium-$${DRONE_COMMIT_SHA} selenium/standalone-chrome
      - docker run --rm --net=container:selenium-$${DRONE_COMMIT_SHA} -e SELENIUM_TCP=tcp://localhost:4444 martin/wait
      - docker run --rm --net=container:app-$${DRONE_COMMIT_SHA} test-$${DRONE_COMMIT_SHA}
      - docker rm -vf "app-$${DRONE_COMMIT_SHA}" "redis-$${DRONE_COMMIT_SHA}"
    when:
      event: push

  install-docker-image-with-githash-tag:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg_euro_tlr_enquiry_form" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-euro-tlr-enquiry-form quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:${DRONE_COMMIT_SHA:0:8}
      - docker push quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:${DRONE_COMMIT_SHA:0:8}
    when:
      event: push

  install-docker-image-from-feature-branch-build:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg_euro_tlr_enquiry_form" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-euro-tlr-enquiry-form quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:${DRONE_BRANCH}
      - docker push quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:${DRONE_BRANCH}
    when:
      branch:
        exclude: master
      event: push

  install-docker-image-from-master-branch-build:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg_euro_tlr_enquiry_form" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-euro-tlr-enquiry-form quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:latest
      - docker push quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:latest
      - docker tag pttg-euro-tlr-enquiry-form quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:build-$${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg_euro_tlr_enquiry_form" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-euro-tlr-enquiry-form quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:$${DRONE_TAG}
      - docker tag pttg-euro-tlr-enquiry-form quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:${DRONE_COMMIT_SHA:0:8}
      - docker push quay.io/ukhomeofficedigital/pttg-euro-tlr-enquiry-form:${DRONE_COMMIT_SHA:0:8}
    when:
      event: tag

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-euro-tlr-enquiry-form.git
      - cd kube-pttg-euro-tlr-enquiry-form
      - git checkout $${KUBE_BRANCH:=master}
    when:
      event: [push, deployment, tag]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:latest
    environment:
      - KUBE_NAMESPACE=pttg-rps-enquiry-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - pttg_rps_dev
    commands:
      - cd kube-pttg-euro-tlr-enquiry-form
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:latest
    environment:
      - KUBE_NAMESPACE=pttg-rps-enquiry-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - pttg_rps_dev
      - pttg_rps_test
      - notify_recipient_notprod
    commands:
      - cd kube-pttg-euro-tlr-enquiry-form
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, test]

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:latest
    environment:
      - KUBE_NAMESPACE=pttg-rps-enquiry-pr
      - ENVIRONMENT=pr
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
      - pttg_rps_pr
      - notify_recipient_prod
    commands:
      - cd kube-pttg-euro-tlr-enquiry-form
      - ./deploy.sh
    when:
      event: deployment
      environment: pr
